name: purge jsdelivr cache

on:
  push:
    branches: [ "*" ]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  purge-jsdelivr-cache:
    runs-on: ubuntu-20.04
    steps:
      - uses: gacts/purge-jsdelivr-cache@v1
        with:
          url: |
            https://cdn.jsdelivr.net/gh/xyz8848/GitHub-i18n-Plugin@main/userscript.js
            https://cdn.jsdelivr.net/gh/xyz8848/GitHub-i18n-Plugin@main/langs/zh-CN.json

  keepalive-workflow:
    name: Keepalive Workflow
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v1
        with:
          use_api: true
