name: purge jsdelivr cache

on:
  push:
    branches: [ ** ]
  workflow_dispatch:

jobs:
    purge-jsdelivr-cache:
      runs-on: ubuntu-20.04
      steps:
        - uses: gacts/purge-jsdelivr-cache@v1
          with:
            url: |
              https://cdn.jsdelivr.net/gh/xyz8848/GitHub-i18n-Plugin@main/userscript.js
              https://cdn.jsdelivr.net/gh/xyz8848/GitHub-i18n-Plugin@main/langs/zh-CN.json